program : 
	g++ ./day2.cpp -O3 -std=c++20 -lfmt -Wno-attributes -fopenmp -fno-exceptions -o ./day2.exe

run :
	echo Input: && day2 ./input.txt && \
	echo Input2: && day2 ./input2.txt

run1 :
	./day2 ./input.txt

run2 :
	./day2 ./input2.txt
